### ISSUE TITLE
Define workflow

### ISSUE THREAD

**Issue by Robert-Freire** [Tokiota/cards-against-humanity-game#4]

**Comment by naulacambra** [comment]
### Mono-player
Here we'll explain the expected workflow for mono-player game.
1. Question page
    1. Player's nickname
        1. Player enter into game
        2. Popup shows up asking for a nickname
        3. Player writes down any string as his nickname
        4. Click on _Accept_ button
    2. First set of cards
        1. Player get **one** random **black** card from _Unused black cards deck_
        2. Player get **five** random **white** cards from _Unused white cards deck_
    3. Make a move
        1. Select N white cards to fulfill N empty spaces at black card
        2. Click on _Done_ button
2. Votation page (dumb)
    1. Select most awkward and despicable generated sentence
    2. Click on _Done_ button
3. Result page
    1. See which sentence has been more votated amongst all generated sentences
    2. Click on _Again_ button
    

Added to this project's Wiki
